# Default values for service-mesh.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
catalog:
  name:
  namespace:
  description:
  publisher:
  registryUrl:
  registryPullSecretName:
  registryPullSecretValue:
  catalogIndexName:
  catalogIndexDigest:
operator:
  namespace: openshift-operators
  name: servicemeshoperator3
  version:
  source: redhat-operators
  sourcenamespace: openshift-marketplace
  installplanapproval: Manual
