{{- if or (eq .Values.ingress.lbtype "alb") (eq .Values.ingress.lbtype "other") }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ default .Values.ingress.name .Values.ingress.deploymentName }}
  namespace: {{ .Values.ingress.namespace }}
  {{- if .Values.ingress.extraDeploymentLabels }}
  labels:
  {{- toYaml .Values.ingress.extraDeploymentLabels | nindent 4 }}
  {{- end }}
spec:
  {{- if .Values.ingress.replicacount }}
  replicas: {{ .Values.ingress.replicacount }}
  {{- end }}
  {{- if .Values.ingress.istioselectors }}
  selector:
    matchLabels:
      {{- if .Values.ingress.istioselectors }}
      {{- toYaml .Values.ingress.istioselectors | nindent 6 }}
      {{- end }}
  {{- end }}
  template:
    metadata:
      annotations:
        inject.istio.io/templates: gateway
      labels:
        {{- if .Values.ingress.istioselectors }}
        {{- toYaml .Values.ingress.istioselectors | nindent 8 }}
        {{- end }}
        {{- if eq .Values.ingress.istioMeshEnrollment "default" }}
        sidecar.istio.io/inject: "true"
        {{- else }}
        istio.io/rev: "{{ .Values.ingress.istioMeshEnrollment }}"
        {{- end }}
        istio.io/gateway: "{{ .Values.ingress.name }}.{{ .Values.ingress.namespace }}"
    spec:
      {{- if .Values.ingress.affinity }}
      affinity:
        {{- if .Values.ingress.affinity.podAffinity }}
        podAffinity:
          {{- toYaml .Values.ingress.affinity.podAffinity | nindent 10 }}
        {{- end }}
        {{- if .Values.ingress.affinity.nodeAffinity }}
        nodeAffinity:
          {{- toYaml .Values.ingress.affinity.nodeAffinity | nindent 10 }}
        {{- end }}
        {{- if .Values.ingress.affinity.podAntiAffinity }}
        podAntiAffinity:
          {{- toYaml .Values.ingress.affinity.podAntiAffinity | nindent 10 }}
        {{- end }}
      {{- end }}
      {{- if .Values.ingress.topologySpreadConstraints }}
      topologySpreadConstraints:
      {{- toYaml .Values.ingress.topologySpreadConstraints | nindent 6 }}
      {{- end }}
      serviceAccountName: {{ .Values.ingress.name }}-service-account
      {{- if .Values.ingress.terminationGracePeriodSeconds }}
      terminationGracePeriodSeconds: {{ .Values.ingress.terminationGracePeriodSeconds }}
      {{- end }}
      tolerations:
      {{- if .Values.ingress.tolerations }}
      {{- toYaml .Values.ingress.tolerations | nindent 6 }}
      {{- end }}
      containers:
      - name: istio-proxy
        image: auto # The image will automatically update each time the pod starts.
        securityContext:
          capabilities:
            drop:
            - ALL
          allowPrivilegeEscalation: false
          privileged: false
          readOnlyRootFilesystem: true
          runAsNonRoot: true
        resources:
        {{- if .Values.ingress.resources }}
        {{- toYaml .Values.ingress.resources | nindent 10 }}
        {{- end }}
        ports:
        - containerPort: 15090
          protocol: TCP
          name: http-envoy-prom
        {{- if .Values.ingress.ports }}
        {{- range .Values.ingress.ports }}
        - containerPort: {{ .port }}
          protocol: {{ .protocol | toString }}
          name: {{ .name }}
        {{- end }}
        {{- end }}
{{- end }}
