{{- if .Values.ingress.pdb.enabled }}
{{- if (eq .Values.ingress.lbtype "nlb") }}
{{- range $lb_subnet, $lb_subnet_zone := .Values.ingress.nlbzonessubnets }}
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  labels:
    {{- if $.Values.ingress.istioselectors }}
    {{- toYaml $.Values.ingress.istioselectors | nindent 4 }}
    {{- end }}
    release: istio
  {{- if $.Values.ingress.nlbAppendZoneToResourceNames }}
  name: {{ printf "%s-%s" $.Values.ingress.pdb.name $lb_subnet_zone }}
  {{- else }}
  name: {{ $.Values.ingress.pdb.name }}
  {{- end }}
  namespace: {{ $.Values.ingress.namespace }}
spec:
  {{- if $.Values.ingress.pdb.minAvailable }}
  minAvailable: {{ $.Values.ingress.pdb.minAvailable }}
  {{- end }}
  {{- if $.Values.ingress.pdb.maxUnavailable }}
  maxUnavailable: {{ $.Values.ingress.pdb.maxUnavailable }}
  {{- end }}
  selector:
    matchLabels:
      {{- toYaml $.Values.ingress.istioselectors | nindent 6 }}
      {{- if $.Values.ingress.extendSelector }}
      {{- if $.Values.ingress.nlbAppendZoneToResourceNames }}
      deploymentName: {{ printf "%s-%s" $.Values.ingress.deploymentName $lb_subnet_zone }}
      {{- else }}
      deploymentName: {{ $.Values.ingress.deploymentName }}
      {{- end }}
      {{- end }}
---
{{- end }}
{{- end }}
{{- end }}
