{{- if .Values.ingress.pdb.enabled }}
{{- if or (eq .Values.ingress.lbtype "alb") (eq .Values.ingress.lbtype "other") }}
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  labels:
    {{- toYaml .Values.ingress.istioselectors | nindent 4 }}
    release: istio
  name: {{ .Values.ingress.pdb.name }}
  namespace: {{ .Values.ingress.namespace }}
spec:
  {{- if .Values.ingress.pdb.minAvailable }}
  minAvailable: {{ .Values.ingress.pdb.minAvailable }}
  {{- end }}
  {{- if .Values.ingress.pdb.maxUnavailable }}
  maxUnavailable: {{ .Values.ingress.pdb.maxUnavailable }}
  {{- end }}
  selector:
    matchLabels:
      {{- toYaml .Values.ingress.istioselectors | nindent 6 }}
      {{- if .Values.ingress.extendSelector }}
      deploymentName: {{ .Values.ingress.deploymentName }}
      {{- end }}
{{- end }}
{{- end }}
