istioconfiguration:
  namespace: istio-system
  name: default # use default for single cp or use cp name for multiple cp on the same cluster
  outboundtrafficpolicy: REGISTRY_ONLY
  istiodiscovery: default # use default for single cp or use cp name for multiple cp on the same cluster
  enablemtls: true
