istioconfiguration:
  namespace: istio-system
  name: default # use default for single cp or use cp name for multiple cp on the same cluster
  peerAuthenticationName:
  outboundTrafficPolicy: REGISTRY_ONLY
  defaultpdb: false
  updateStrategyType: InPlace
  enableNetworkPolicy: true
  pilot:
    env:
    enabled: true
    autoscale:
      enabled: "false"
      autoscaleMin: 1
      autoscaleMax: 3
      cpu:
        targetavgutil: 80
      memory:
        targetavgutil: 80
    replicacount: 1
    nodeselector: { "ibm-cloud.kubernetes.io/worker-pool-name": "default" }
    affinity:
    tolerations:
    resources:
    taint:
      enabled: true
      namespace: istio-cni
  meshConfig:
    enableAutoMTLS: true
    tcpKeepalive:
    connectTimeout:
    ingressControllerMode: STRICT
    ingressService: istio-ingressgateway
    ingressSelector: ingressgateway
    outboundTrafficPolicy: REGISTRY_ONLY
    discoverySelectors:
    - matchLabels: {"istio-discovery" : "enabled"} # use default for single cp or use cp name for multiple cp on the same cluster
    accessLogFile: "/dev/stdout"
    accessLogFormat: "[%START_TIME%] [%REQ(:AUTHORITY)%] [%BYTES_RECEIVED%] [%BYTES_SENT%] [%DOWNSTREAM_LOCAL_ADDRESS%] [%DOWNSTREAM_LOCAL_ADDRESS%] [%DOWNSTREAM_REMOTE_ADDRESS%] [%DOWNSTREAM_TLS_VERSION%] [%DURATION%] [%REQUEST_DURATION%] [%RESPONSE_DURATION%] [%RESPONSE_TX_DURATION%] [%DYNAMIC_METADATA(istio.mixer:status)%] [%REQ(:METHOD)%] [%REQ(X-ENVOY-ORIGINAL-PATH?:PATH)%] [%PROTOCOL%] [%REQ(X-REQUEST-ID)%] [%REQUESTED_SERVER_NAME%] [%RESPONSE_CODE%] [%RESPONSE_CODE_DETAILS%] [%RESPONSE_FLAGS%] [%ROUTE_NAME%] [%START_TIME%] [%UPSTREAM_CLUSTER%] [%UPSTREAM_HOST%] [%UPSTREAM_LOCAL_ADDRESS%] [%RESP(X-ENVOY-UPSTREAM-SERVICE-TIME)%] [%UPSTREAM_TRANSPORT_FAILURE_REASON%] [%REQ(USER-AGENT)%] [%REQ(X-FORWARDED-FOR)%] [%REQ(X-ENVOY-ATTEMPT-COUNT)%]"
    accessLogEncoding: JSON
    extensionProviders:
