apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.configMap.name }}
  namespace: {{ .Values.namespace }}
data:
  deployment: |
    metadata:
      {{- if .Values.configMap.deployment.labels }}
      labels:
        {{- toYaml .Values.configMap.deployment.labels | nindent 8 }}
      {{- end }}
      {{- if .Values.configMap.deployment.annotations }}
      annotations:
        {{- toYaml .Values.configMap.deployment.annotations | nindent 8 }}
      {{- end }}

    spec:
      {{- if .Values.configMap.deployment.replicas }}
      replicas: {{ .Values.configMap.deployment.replicas }}
      {{- end }}

      template:
        metadata:
          {{- if .Values.configMap.deployment.podLabels }}
          labels:
            {{- toYaml .Values.configMap.deployment.podLabels | nindent 12 }}
          {{- end }}
          {{- if .Values.configMap.deployment.podAnnotations }}
          annotations:
            {{- toYaml .Values.configMap.deployment.podAnnotations | nindent 12 }}
          {{- end }}

        spec:
          {{- if .Values.configMap.deployment.affinity }}
          affinity:
            {{- if .Values.configMap.deployment.affinity.podAffinity }}
            podAffinity:
              {{- toYaml .Values.configMap.deployment.affinity.podAffinity | nindent 14 }}
            {{- end }}
            {{- if .Values.configMap.deployment.affinity.nodeAffinity }}
            nodeAffinity:
              {{- toYaml .Values.configMap.deployment.affinity.nodeAffinity | nindent 14 }}
            {{- end }}
            {{- if .Values.configMap.deployment.affinity.podAntiAffinity }}
            podAntiAffinity:
              {{- toYaml .Values.configMap.deployment.affinity.podAntiAffinity | nindent 14 }}
            {{- end }}
          {{- end }}

          tolerations:
          {{- if .Values.configMap.deployment.tolerations }}
          {{- toYaml .Values.configMap.deployment.tolerations | nindent 10 }}
          {{- end }}

          containers:
          - name: istio-proxy
            resources:
            {{- if .Values.configMap.deployment.resources }}
            {{- toYaml .Values.configMap.deployment.resources | nindent 14 }}
            {{- end }}

  service: |
    metadata:
      {{- if .Values.configMap.service.labels }}
      labels:
        {{- toYaml .Values.configMap.service.labels | nindent 8 }}
      {{- end }}
      {{- if .Values.configMap.service.annotations }}
      annotations:
        {{- toYaml .Values.configMap.service.annotations | nindent 8 }}
      {{- end }}
