apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: {{ .Values.gateway.name }}
  namespace: {{ .Values.namespace }}
  labels:
    istio.io/waypoint-for: {{ .Values.gateway.waypointFor }}
spec:
  gatewayClassName: istio-waypoint

  infrastructure:
    {{- if .Values.gateway.labels }}
    labels:
      {{- toYaml .Values.gateway.labels | nindent 6 }}
    {{- end }}
    {{- if .Values.gateway.annotations }}
    annotations:
      {{- toYaml .Values.gateway.annotations | nindent 6 }}
    {{- end }}

    parametersRef:
      group: ""
      kind: ConfigMap
      name: {{ .Values.configMap.name }}

  listeners:
  - name: mesh
    protocol: HBONE
    port: 15008
    allowedRoutes:
      namespaces:
        from: {{ .Values.gateway.allowedRoutes }}
