namespace: istio-system

configMap:
  name: waypoint-config
  deployment:
    name: null
    labels: {}
    annotations: {}
    replicas: null
    podLabels: {}
    podAnnotations: {}
    tolerations: []
    affinity: {}
    resources: {}
  service:
    name: null
    labels: {}
    annotations: {}

gateway:
  name: waypoint
  waypointFor: service
  allowedRoutes: All
  labels: {}
  annotations: {}
