# Allow outside traffic to access the gateway
# This is optional, only needed in case your cluster contains restrictive NetworkPolicies
#apiVersion: networking.k8s.io/v1
#kind: NetworkPolicy
#metadata:
#  name: gatewayegress
#spec:
#  podSelector:
#    matchLabels:
#      istio: egressgateway
#  egress:
#    - {}
#  policyTypes:
#  - Egress
