apiVersion: v1
kind: ServiceAccount
metadata:
  name: egress-{{ .Values.egress.name }}
  namespace: {{ .Values.egress.namespace }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: egress-{{ .Values.egress.name }}
  namespace: {{ .Values.egress.namespace }}
rules:
- apiGroups: [""]
  resources: ["secrets"]
  verbs: ["get", "watch", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: egress-{{ .Values.egress.name }}
  namespace: {{ .Values.egress.namespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: egress-{{ .Values.egress.name }}
subjects:
- kind: ServiceAccount
  name: egress-{{ .Values.egress.name }}
