# https://github.com/istio-ecosystem/sail-operator/blob/main/docs/api-reference/sailoperator.io.md
apiVersion: sailoperator.io/v1
kind: Istio
metadata:
  name: {{ .Values.istioconfiguration.name }}
spec:
  namespace: {{ .Values.istioconfiguration.namespace }}
  updateStrategy:
    inactiveRevisionDeletionGracePeriodSeconds: 30
    type: {{ .Values.istioconfiguration.updateStrategyType }}
  global:
    logAsJson: true
    istioNamespace: {{ .Values.istioconfiguration.namespace }}
    defaultPodDisruptionBudget:
      enabled: {{ .Values.istioconfiguration.defaultpdb }}
    networkPolicy:
      enabled: {{ .Values.istioconfiguration.enableNetworkPolicy }}
  values:
    outboundTrafficPolicy: {{ .Values.istioconfiguration.outboundTrafficPolicy }}
    pilot:
      enabled: {{ .Values.istioconfiguration.pilot.enabled }}
      autoscaleEnabled: {{ .Values.istioconfiguration.pilot.autoscale.enabled }}
      replicaCount: {{ .Values.istioconfiguration.pilot.replicacount }}
      {{- if (.Values.istioconfiguration.pilot.autoscale).enabled | default false -}}
      {{- if .Values.istioconfiguration.pilot.autoscale.autoscaleMin }}
      autoscaleMin: {{ .Values.istioconfiguration.pilot.autoscale.autoscaleMin }}
      {{- end }}
      {{- if .Values.istioconfiguration.pilot.autoscale.autoscaleMax }}
      autoscaleMax: {{ .Values.istioconfiguration.pilot.autoscale.autoscaleMax }}
      {{- end }}
      {{- if .Values.istioconfiguration.pilot.autoscale.cpu }}
      {{- if .Values.istioconfiguration.pilot.autoscale.cpu.targetavgutil }}
      cpu:
        targetAverageUtilization: {{ .Values.istioconfiguration.pilot.autoscale.cpu.targetavgutil }}
      {{- end }}
      {{- end }}
      {{- if .Values.istioconfiguration.pilot.autoscale.memory }}
      {{- if .Values.istioconfiguration.pilot.autoscale.memory.targetavgutil }}
      memory:
        targetAverageUtilization: {{ .Values.istioconfiguration.pilot.autoscale.memory.targetavgutil }}
      {{- end }}
      {{- end }}
      {{- end }}
      {{- if .Values.istioconfiguration.pilot.nodeselector }}
      nodeSelector:
      {{- toYaml .Values.istioconfiguration.pilot.nodeselector | nindent 8 }}
      {{- end }}
      {{- if .Values.istioconfiguration.pilot.resources }}
      resources:
      {{- toYaml .Values.istioconfiguration.pilot.resources | nindent 8 }}
      {{- end }}
      {{- if .Values.istioconfiguration.pilot.affinity }}
      affinity:
      {{- toYaml .Values.istioconfiguration.pilot.affinity | nindent 8 }}
      {{- end }}
      {{- if .Values.istioconfiguration.pilot.tolerations }}
      tolerations:
      {{- toYaml .Values.istioconfiguration.pilot.tolerations | nindent 8 }}
      {{- end }}
      {{- if .Values.istioconfiguration.pilot.env }}
      env:
      {{- toYaml .Values.istioconfiguration.pilot.env | nindent 8 }}
      {{- end }}
    {{- if .Values.istioconfiguration.meshConfig }}
    meshConfig: # https://github.com/istio-ecosystem/sail-operator/blob/main/docs/api-reference/sailoperator.io.md#meshconfig
      {{- if .Values.istioconfiguration.meshConfig.enableAutoMTLS }}
      enableAutoMtls: {{ .Values.istioconfiguration.meshConfig.enableAutoMTLS }}
      {{- end }}
      {{- if .Values.istioconfiguration.meshConfig.connectTimeout }}
      connectTimeout: {{ .Values.istioconfiguration.meshConfig.connectTimeout }}
      {{- end }}
      {{- if .Values.istioconfiguration.meshConfig.tcpKeepalive }}
      tcpKeepalive:
      {{- toYaml .Values.istioconfiguration.meshConfig.tcpKeepalive | nindent 8 }}
      {{- end }}
      {{- if .Values.istioconfiguration.meshConfig.ingressControllerMode }}
      ingressControllerMode: {{ .Values.istioconfiguration.meshConfig.ingressControllerMode }}
      {{- end }}
      {{- if .Values.istioconfiguration.meshConfig.ingressService }}
      ingressService: {{ .Values.istioconfiguration.meshConfig.ingressService | quote }}
      {{- end }}
      {{- if .Values.istioconfiguration.meshConfig.ingressSelector }}
      ingressSelector: {{ .Values.istioconfiguration.meshConfig.ingressSelector | quote }}
      {{- end }}
      {{- if .Values.istioconfiguration.meshConfig.accessLogFile }}
      accessLogFile: {{ .Values.istioconfiguration.meshConfig.accessLogFile | quote }}
      {{- end }}
      {{- if .Values.istioconfiguration.meshConfig.accessLogFormat }}
      accessLogFormat: {{ .Values.istioconfiguration.meshConfig.accessLogFormat | quote }}
      {{- end }}
      {{- if .Values.istioconfiguration.meshConfig.accessLogEncoding }}
      accessLogEncoding: {{ .Values.istioconfiguration.meshConfig.accessLogEncoding }}
      {{- end }}
      {{- if .Values.istioconfiguration.meshConfig.outboundTrafficPolicy }}
      outboundTrafficPolicy:
        mode: {{ .Values.istioconfiguration.meshConfig.outboundTrafficPolicy }}
      {{- end }}
      {{- if .Values.istioconfiguration.meshConfig.discoverySelectors }}
      discoverySelectors:
        {{- toYaml .Values.istioconfiguration.meshConfig.discoverySelectors | nindent 8 }}
      {{- end }}
      {{- if .Values.istioconfiguration.meshConfig.defaultConfig }}
      defaultConfig:
        {{- if .Values.istioconfiguration.meshConfig.defaultConfig.proxyMetadata }}
        proxyMetadata:
          {{- toYaml .Values.istioconfiguration.meshConfig.defaultConfig.proxyMetadata | nindent 10 }}
        {{- end }}
      {{- end }}
      {{- if .Values.istioconfiguration.meshConfig.meshMTLS }}
      meshMTLS:
        {{- toYaml .Values.istioconfiguration.meshConfig.meshMTLS | nindent 8 }}
      {{- end }}
      {{- if .Values.istioconfiguration.meshConfig.tlsDefaults }}
      tlsDefaults:
        {{- toYaml .Values.istioconfiguration.meshConfig.tlsDefaults | nindent 8 }}
      {{- end }}
      {{- if .Values.istioconfiguration.meshConfig.extensionProviders }}
      extensionProviders:
      {{- toYaml .Values.istioconfiguration.meshConfig.extensionProviders | nindent 8 }}
      {{- end }}
    {{- end }}
