apiVersion: sailoperator.io/v1
kind: Istio
metadata:
  name: {{ .Values.istioconfiguration.name }}
spec:
  namespace: {{ .Values.istioconfiguration.namespace }}
  updateStrategy:
    inactiveRevisionDeletionGracePeriodSeconds: 30
    type: InPlace
  global:
    defaultPodDisruptionBudget:
      enabled: false
  values:
    outboundTrafficPolicy: {{ .Values.istioconfiguration.outboundtrafficpolicy }}
    pilot:
      enabled : true
      autoscaleEnabled: false
      replicaCount: 2
      autoscaleMin: 2   # <-- number of desired min replicas
      autoscaleMax: 5   # <-- number of desired max replicas
      # nodeSelector: # https://kubernetes.io/docs/concepts/scheduling-eviction/assign-pod-node/#nodeselector
      cpu:
        targetAverageUtilization: 80 # <-- target CPU utilization for autoscaling
      memory:
        targetAverageUtilization: 80 # <-- target memory utilization for autoscaling
      resources:
        requests:
          cpu: 100m
          memory: 1024Mi
        limits:
          cpu: 100m
          memory: 1024Mi
      affinity:
        nodeAffinity: {{ .Values.istioconfiguration.nodeAffinity }} # to use toyaml
        podAffinity: {{ .Values.istioconfiguration.podAffinity }} # to use toyaml
        podAntiAffinity: {{ .Values.istioconfiguration.podAntiAffinity }} # to use toyaml
        {{- if .Values.istioconfiguration.tolerations }}
        tolerations: {{ .Values.istioconfiguration.tolerations }} # https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.25/#toleration-v1-core
        {{- end }}
        {{- if .Values.istioconfiguration.taint }}
        taint: {{ .Values.istioconfiguration.taint }} # https://github.com/istio-ecosystem/sail-operator/blob/main/docs/api-reference/sailoperator.io.md#pilottaintcontrollerconfig
        {{- end }}
    meshConfig: # https://github.com/istio-ecosystem/sail-operator/blob/main/docs/api-reference/sailoperator.io.md#meshconfig
      connectTimeout: 10s
      tcpKeepalive: # https://github.com/istio-ecosystem/sail-operator/blob/main/docs/api-reference/sailoperator.io.md#connectionpoolsettingstcpsettingstcpkeepalive
        probes: 9
        time: 7200s
        interval: 75s
      ingressControllerMode: STRICT # https://github.com/istio-ecosystem/sail-operator/blob/main/docs/api-reference/sailoperator.io.md#meshconfigingresscontrollermode
      ingressService: istio-ingressgateway
      ingressSelector: ingressgateway
      enableTracing: false
      # accessLogFile: /dev/stdout
      # accessLogFormat:
      # accessLogEncoding: JSON
      outboundTrafficPolicy:
        mode: {{ .Values.istioconfiguration.outboundtrafficpolicy }}
      discoverySelectors:
      - matchLabels:
          istio-discovery: {{ .Values.istioconfiguration.istiodiscovery }}
