{{- if .Values.istioconfiguration.meshConfig.enableAutoMTLS }}
{{- if eq (default .Values.istioconfiguration.meshConfig.enableAutoMTLS true) true }}
apiVersion: security.istio.io/v1
kind: PeerAuthentication
metadata:
  name: {{ .Values.istioconfiguration.name }}-peerauthentication
  namespace: {{ .Values.istioconfiguration.namespace }}
spec:
  mtls:
    mode: STRICT
{{- end }}
{{- end }}
