{{- if .Values.istioconfiguration.meshConfig.enableAutoMTLS }}
{{- if eq (default .Values.istioconfiguration.meshConfig.enableAutoMTLS true) true }}
apiVersion: security.istio.io/v1
kind: PeerAuthentication
metadata:
  name: {{ default (printf "%s-peerauthentication" .Values.istioconfiguration.name) .Values.istioconfiguration.peerAuthenticationName }}
  namespace: {{ .Values.istioconfiguration.namespace }}
spec:
  mtls:
    mode: STRICT
{{- end }}
{{- end }}
