ztunnel:
  namespace: ztunnel
  resources:
    # limits:
    #   cpu: 500m
    #   memory: 256Mi
    # requests:
    #   cpu: 100m
    #   memory: 128Mi
  tolerations: []
    # - key: "key1"
    #   operator: "Equal"
    #   value: "value1"
    #   effect: "NoSchedule"
