apiVersion: networking.istio.io/v1
kind: VirtualService
metadata:
  name: httpbin
  namespace: {{ .Values.namespace }}
spec:
  hosts:
  - "*"
  gateways:
  - httpbin-gateway
  http:
  - match:
    - uri:
        exact: /get
    route:
    - destination:
        host: httpbin
        port:
          number: 8000
