{{- if .Values.catalog }}
{{- if not (.Values.catalog.name | empty)}}
{{- if not (quote .Values.catalog.registryPullSecretValue | empty) }}
apiVersion: v1
data:
  .dockerconfigjson: {{ .Values.catalog.registryPullSecretValue | toJson | b64enc }}
kind: Secret
metadata:
  name: {{ .Values.catalog.registryPullSecretName }}
  namespace: {{ .Values.catalog.namespace }}
type: kubernetes.io/dockerconfigjson
{{- end }}
{{- end }}
{{- end }}
