apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  labels:
    operators.coreos.com/servicemeshoperator3.openshift-operators: ""
  name: {{ .Values.operator.name }}
  namespace: {{ .Values.operator.namespace }}
spec:
  channel: stable
  installPlanApproval: {{ .Values.operator.installplanapproval }}
  name: {{ .Values.operator.name }}
  source: {{ .Values.operator.source }}
  sourceNamespace: {{ .Values.operator.sourcenamespace }}
  # startingCSV:           servicemeshoperator3.v3.1.3
  # startingCSV: servicemeshoperator3.v3.0.1
  # startingCSV: servicemeshoperator3.v3.0.3
