apiVersion: sailoperator.io/v1alpha1
kind: ZTunnel
metadata:
  name: default
spec:
  namespace: {{ .Values.ztunnel.namespace }}
  profile: ambient
  values:
    ztunnel:
      resources:
      {{- if .Values.ztunnel.resources }}
      {{- toYaml .Values.ztunnel.resources | nindent 8 }}
      {{- end }}
      {{- if .Values.ztunnel.tolerations }}
      tolerations:
      {{- toYaml .Values.ztunnel.tolerations | nindent 8 }}
      {{- end }}
